import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import {createHmac} from 'node:crypto';
import {openDatabase} from '../server/db.mjs';
import {createApp} from '../server/app.mjs';
import {storage} from '../server/storage.mjs';
import {hash,uuid} from '../server/security.mjs';
import {verifyStripe} from '../server/billing.mjs';
import {schedule} from '../server/events.mjs';
import {folder} from '../shared/plans.js';
test('full isolated customer, photo and export flow',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'lumiq-test-')),db=await openDatabase({memory:true}),origin='http://127.0.0.1:5799';
 const app=await createApp({db,files:storage({root}),origin});let cookie='',e,g,mid;
 const call=async(p,body,method=body?'POST':'GET',headers={})=>{const r=await app.handle(new Request(origin+'/api'+p,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,...headers},...(body?{body:JSON.stringify(body)}:{})}));return {r,data:await r.json()};};
 try{
 await t.test('automatic clocks and readable names with unique IDs',()=>{assert.equal(schedule({start:'2026-09-13T18:00',end:'2026-09-13T23:00',time_zone:'America/New_York'}).starts_at,'2026-09-13T22:00:00.000Z');assert.throws(()=>schedule({start:'2026-03-29T03:30',end:'2026-03-29T05:00',time_zone:'Europe/Riga'}));assert.match(folder('Sophie & Oliver',uuid()),/^sophie-oliver--/);});
 await t.test('register, verify once, login and session',async()=>{assert.equal((await call('/auth/register',{name:'Owner',email:'owner@example.test',password:'Test-password-123!'})).r.status,200);assert.equal((await call('/auth/login',{email:'owner@example.test',password:'Test-password-123!'})).r.status,403);const inbox=await call('/local/inbox'),token=new URL(inbox.data[0].body).searchParams.get('token');assert.equal((await call('/auth/consume',{token})).r.status,200);assert.equal((await call('/auth/consume',{token})).r.status,400);const login=await call('/auth/login',{email:'owner@example.test',password:'Test-password-123!'});cookie=login.r.headers.get('set-cookie').split(';')[0];assert((await call('/auth/session')).data.user);});
 await t.test('draft preview and printable QR designs are safe and readable',async()=>{const start=new Date(Date.now()-3600000).toISOString().slice(0,16),end=new Date(Date.now()+3600000).toISOString().slice(0,16);e=(await call('/events',{name:'Integration party',start,end,time_zone:'UTC'})).data;assert(e.id);const preview=(await call(`/events/${e.id}/preview`,{})).data,previewUrl=new URL(preview.url),secret=previewUrl.searchParams.get('preview');assert.equal(preview.expires_in,900);const page=await call(`/guest/${e.slug}?preview=${encodeURIComponent(secret)}`);assert.equal(page.r.status,200);assert.equal(page.data.preview,true);assert.equal(page.data.state,'preview');assert.equal((await call(`/guest/${e.slug}/join?preview=${encodeURIComponent(secret)}`,{name:'Blocked'})).r.status,403);for(const template of ['garden','vintage','celebration','modern']){const qr=await app.handle(new Request(`${origin}/api/events/${e.id}/qr?preview=${encodeURIComponent(secret)}&format=square&template=${template}`,{headers:{Origin:origin,Cookie:cookie}}));assert.equal(qr.status,200);assert.equal(qr.headers.get('content-type'),'image/png');assert((await qr.arrayBuffer()).byteLength>10000);}const background=await sharp({create:{width:600,height:900,channels:3,background:'#d7e7dd'}}).png().toBuffer();assert.equal((await call(`/events/${e.id}/qr-background`,{data:background.toString('base64')})).r.status,200);const custom=await app.handle(new Request(`${origin}/api/events/${e.id}/qr?preview=${encodeURIComponent(secret)}&format=a5&template=custom`,{headers:{Origin:origin,Cookie:cookie}}));assert.equal(custom.status,200);assert((await custom.arrayBuffer()).byteLength>10000);});
 await t.test('publish, pause and guest entry',async()=>{assert.equal((await call(`/events/${e.id}/action`,{action:'publish'})).r.status,200);assert.equal((await call('/admin')).r.status,403);await call(`/events/${e.id}/action`,{action:'pause'});assert.equal((await call(`/guest/${e.slug}/join`,{name:'Blocked'})).r.status,409);await call(`/events/${e.id}/action`,{action:'resume'});g=(await call(`/guest/${e.slug}/join`,{name:'Guest One'})).data;assert(g.token);});
 await t.test('file pair validation, stable retries, gallery isolation',async()=>{const photo=await sharp({create:{width:80,height:60,channels:3,background:'#397755'}}).webp().toBuffer();mid=uuid();const body={id:mid,name:'test.webp',bytes:photo.length,thumbnail_bytes:photo.length,checksum:hash(photo),thumbnail_checksum:hash(photo)},headers={'X-Guest-Token':g.token};const r=await call(`/guest/${e.slug}/reserve`,body,'POST',headers);assert.equal(r.r.status,200);assert.match(r.data.object_key,/integration-party--.*\/guests\/guest-one--/);assert.equal((await call(`/guest/${e.slug}/reserve`,body,'POST',headers)).data.object_key,r.data.object_key);assert.equal((await call(`/guest/${e.slug}/finalize`,{id:mid},'POST',headers)).r.status,409);for(const kind of ['photo','thumb'])assert.equal((await app.handle(new Request(`${origin}/api/guest/${e.slug}/content/${mid}/${kind}`,{method:'PUT',headers:{Origin:origin,...headers},body:photo}))).status,200);assert.equal((await call(`/guest/${e.slug}/finalize`,{id:mid},'POST',headers)).r.status,200);assert.equal((await call(`/guest/${e.slug}/finalize`,{id:mid},'POST',headers)).r.status,200);assert.equal((await call(`/events/${e.id}/photos`)).data.total,1);assert.equal((await app.handle(new Request(`${origin}/api/photos/${mid}/photo`))).status,403);});
 await t.test('sharing revokes access, exports survive reload',async()=>{await db.query("update events set starts_at=now()-interval '2 hours',ends_at=now()-interval '1 hour' where id=$1",[e.id]);assert.equal((await call(`/events/${e.id}/action`,{action:'share',enabled:true,days:7})).r.status,200);assert.equal((await call(`/guest/${e.slug}/photos`)).data.total,1);await call(`/events/${e.id}/action`,{action:'share',enabled:false,days:7});assert.equal((await call(`/guest/${e.slug}/photos`)).r.status,403);const job=(await call(`/events/${e.id}/export`,{})).data;await app.jobs.tick();const ready=(await call(`/jobs/${job.id}`)).data;assert.equal(ready.status,'ready');assert.equal(ready.result.count,1);assert.equal((await call(`/events/${e.id}/export`,{})).data.id,job.id);});
 await t.test('verified payment simulation and deduplication',async()=>{const o=(await call('/billing/checkout',{plan:'gathering'})).data;assert.equal((await call('/billing')).data.subscription.plan,'trial');assert.equal((await call('/billing/simulate',{order:o.order,outcome:'success'})).r.status,200);assert.equal((await call('/billing/simulate',{order:o.order,outcome:'success'})).data.duplicate,true);assert.equal((await call('/billing')).data.subscription.plan,'gathering');await call('/billing/cancel',{});assert.equal((await call('/billing')).data.subscription.cancel_at_end,true);});
 await t.test('CSRF and wrong-account access denied',async()=>{await call('/auth/register',{name:'Other',email:'other@example.test',password:'Test-password-123!'});const mail=(await call('/local/inbox')).data.find(m=>m.recipient==='other@example.test');await call('/auth/consume',{token:new URL(mail.body).searchParams.get('token')});const login=await call('/auth/login',{email:'other@example.test',password:'Test-password-123!'});assert.equal((await call(`/events/${e.id}`,null,'GET',{Cookie:login.r.headers.get('set-cookie').split(';')[0]})).r.status,404);assert.equal((await app.handle(new Request(origin+`/api/events/${e.id}/action`,{method:'POST',headers:{Origin:'https://attacker.invalid',Cookie:cookie},body:JSON.stringify({action:'delete',confirm:e.name})}))).status,403);});
 await t.test('metadata deletion followed by object cleanup',async()=>{assert.equal((await call(`/events/${e.id}/photos`,{ids:[mid]},'DELETE')).r.status,200);assert.equal((await call(`/events/${e.id}/photos`)).data.total,0);await app.jobs.tick();const m=(await db.query('select * from media where id=$1',[mid])).rows[0];await assert.rejects(app.files.get(m.object_key));});
 }finally{await db.close();await rm(root,{recursive:true,force:true});}
});
test('Stripe signature validation rejects tampering and expired replay',()=>{const body=JSON.stringify({id:'evt_test'}),secret='test-only',time=Math.floor(Date.now()/1000),sig=createHmac('sha256',secret).update(`${time}.${body}`).digest('hex');assert.equal(verifyStripe(body,`t=${time},v1=${sig}`,secret).id,'evt_test');assert.throws(()=>verifyStripe(body+' ',`t=${time},v1=${sig}`,secret));assert.throws(()=>verifyStripe(body,`t=${time-1000},v1=${sig}`,secret));});
