import {profileDetails} from './profile.mjs';
import {uuid,token,hash,passwordHash,passwordMatches,email,text,requireThat,cookies,confirmedPassword} from './security.mjs';
import {queueMessage} from './notifications.mjs';
import {localized} from './locale.mjs';
export function authService(db,{origin,local=true}) {
 const mail=(account,subject,body,dedupe=null)=>queueMessage(db,account,subject,body,dedupe);
 const issue=async(account,purpose,payload={})=>{const t=token();await db.query('insert into auth_tokens values($1,$2,$3,$4,now()+interval \'1 hour\')',[hash(t),account.id,purpose,payload]);const en=purpose==='verify'?'Verify your Lumiq email':purpose==='email'?'Confirm your new email':'Reset your password',lv=purpose==='verify'?'Apstiprini Lumiq e-pastu':purpose==='email'?'Apstiprini jauno e-pastu':'Atjauno paroli';await mail(account,localized(account,en,lv),`${origin}/auth/${purpose}?token=${t}`);};
 return {
  mail,
  async user(req){const t=cookies(req.headers.get('cookie')).lumiq_session;if(!t)return null;return(await db.query('select a.* from accounts a join sessions s on s.account_id=a.id where s.token_hash=$1 and s.expires_at>now() and a.deleted_at is null',[hash(t)])).rows[0]||null;},
  async register(input){const details=profileDetails(input);if(input.password_confirm!==undefined)requireThat(input.password===input.password_confirm,400,'Passwords do not match.');const account={id:uuid(),email:email(input.email),preferences:{service:true,marketing:false,locale:input.locale==='lv'?'lv':'en'},...details};const password=await passwordHash(input.password);await db.transaction(async tx=>{await tx.query('insert into accounts(id,email,name,password_hash,profile,preferences) values($1,$2,$3,$4,$5,$6)',[account.id,account.email,account.name,password,account.profile,account.preferences]);await tx.query('insert into subscriptions(account_id) values($1)',[account.id]);});await issue(account,'verify');return {message:'Check your email to verify your account.'};},
  async login(input){const account=(await db.query('select * from accounts where email=$1 and deleted_at is null',[email(input.email)])).rows[0];requireThat(account&&await passwordMatches(input.password,account.password_hash),401,'Email or password is incorrect.');requireThat(account.verified,403,'Verify your email before signing in.');const t=token();await db.query('insert into sessions(token_hash,account_id,expires_at) values($1,$2,now()+interval \'7 days\')',[hash(t),account.id]);return {cookie:`lumiq_session=${t}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${local?'':'; Secure'}`,user:{id:account.id,name:account.name,email:account.email,role:account.role}};},
  async logout(req){await db.query('delete from sessions where token_hash=$1',[hash(cookies(req.headers.get('cookie')).lumiq_session||'')]);},
  async requestReset(input){const account=(await db.query('select * from accounts where email=$1 and deleted_at is null',[email(input.email)])).rows[0];if(account)await issue(account,'reset');return {message:'If the account exists, a reset email is on its way.'};},
  async consume(input){const key=hash(text(input.token,128));await db.transaction(async tx=>{const t=(await tx.query('delete from auth_tokens where token_hash=$1 and expires_at>now() returning *',[key])).rows[0];requireThat(t,400,'This link is invalid or expired. Request a new one.');if(t.purpose==='verify')await tx.query('update accounts set verified=true where id=$1',[t.account_id]);else if(t.purpose==='reset'){const password=confirmedPassword(input);await tx.query('update accounts set password_hash=$1 where id=$2',[await passwordHash(password),t.account_id]);await tx.query('delete from sessions where account_id=$1',[t.account_id]);}else if(t.purpose==='email'){await tx.query('update accounts set email=$1 where id=$2',[t.payload.email,t.account_id]);await tx.query('delete from sessions where account_id=$1',[t.account_id]);}});return {message:'Your account has been updated. You can sign in.'};},
  async changePassword(user,input){requireThat(input.new_password===input.password_confirm,400,'Passwords do not match.');const next=await passwordHash(input.new_password);await db.transaction(async tx=>{const current=(await tx.query('select password_hash from accounts where id=$1 and deleted_at is null for update',[user.id])).rows[0];requireThat(current&&await passwordMatches(input.password,current.password_hash),403,'Confirm your current password.');await tx.query('update accounts set password_hash=$1 where id=$2',[next,user.id]);await tx.query('delete from sessions where account_id=$1',[user.id]);await tx.query('delete from auth_tokens where account_id=$1',[user.id]);});await mail(user,localized(user,'Password changed','Parole mainīta'),localized(user,'Your password was changed. Sign in again on your devices. Contact support if this was not you.','Tava parole tika mainīta. Ienāc vēlreiz savās ierīcēs. Ja to nedarīji tu, sazinies ar atbalstu.'));return {message:'Password changed. Sign in again.'};},
  async update(user,input){requireThat(await passwordMatches(input.password,user.password_hash),403,'Confirm your current password.');const details=profileDetails(input,user.profile);await db.query('update accounts set name=$1,preferences=$2,profile=$4 where id=$3',[details.name,{service:true,marketing:input.marketing===true,locale:input.locale==='lv'?'lv':'en'},user.id,details.profile]);if(input.email&&email(input.email)!==user.email){const address=email(input.email);await issue({...user,email:address},'email',{email:address});}return {message:'Profile saved. Check your new inbox if you changed your email.'};}
 };
}
