import {uuid,text,requireThat,hash} from './security.mjs';
import sharp from 'sharp';
import {DateTime} from 'luxon';
import {eventState} from '../shared/plans.js';
export function mediaService(db,files,events){
 const ready=async(id)=>{const m=(await db.query('select * from media where id=$1',[id])).rows[0];requireThat(m,404,'Photo not found.');return m;};
 return {
  ready,
  async discard(e,g,id){return db.transaction(async tx=>{const m=(await tx.query("update media set status='deleted',deleted_at=now() where id=$1 and event_id=$2 and guest_id=$3 and status='pending' returning id",[id,e.id,g.id])).rows[0];if(m)await tx.query("insert into jobs(id,owner_id,event_id,type,payload,available_at) values($1,$2,$3,'media-cleanup',$4,now()+interval '6 minutes')",[uuid(),e.owner_id,e.id,JSON.stringify({ids:[id]})]);return{ok:true};});},
  async reserve(e,g,input){requireThat(eventState(e)==='live',409,'This event is closed for uploads.');const id=text(input.id,36);requireThat(/^[0-9a-f-]{36}$/i.test(id),400,'Invalid photo identifier.');const bytes=Number(input.bytes),thumb=Number(input.thumbnail_bytes);requireThat(bytes>0&&bytes<=6291456&&thumb>0&&thumb<=1048576,413,'The optimized photo must be under 6 MB.');return db.transaction(async tx=>{e=(await tx.query('select * from events where id=$1 for update',[e.id])).rows[0];requireThat(eventState(e)==='live',409,'This event is closed for uploads.');const previous=(await tx.query('select * from media where id=$1',[id])).rows[0];if(previous){requireThat(previous.event_id===e.id&&previous.guest_id===g.id&&previous.bytes===bytes&&previous.thumbnail_bytes===thumb&&previous.checksum===input.checksum&&previous.thumbnail_checksum===input.thumbnail_checksum&&previous.status!=='deleted',409,'This upload cannot be replaced.');return previous;}
   const used=(await tx.query("select count(*)::int as photos,coalesce(sum(bytes+thumbnail_bytes),0)::bigint as bytes from media where event_id=$1 and status in ('pending','uploaded')",[e.id])).rows[0];requireThat(used.photos<e.entitlement.photos&&Number(used.bytes)+bytes+thumb<=e.entitlement.bytes,409,'This event has reached its photo or storage allowance.');for(const h of [input.checksum,input.thumbnail_checksum])requireThat(/^[a-f0-9]{64}$/.test(h),400,'Photo validation failed.');const key=`${g.storage_prefix}/photo-${id}.webp`,thumbnail=`${g.storage_prefix}/thumb-${id}.webp`;return(await tx.query('insert into media(id,event_id,guest_id,object_key,thumbnail_key,name,bytes,thumbnail_bytes,checksum,thumbnail_checksum) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *',[id,e.id,g.id,key,thumbnail,text(input.name,180),bytes,thumb,input.checksum,input.thumbnail_checksum])).rows[0];});},
  async upload(e,g,id,kind,bytes){const m=await ready(id);requireThat(m.event_id===e.id&&m.guest_id===g.id&&m.status==='pending'&&eventState(e)==='live',409,'This upload is no longer available.');const thumb=kind==='thumb';requireThat(['thumb','photo'].includes(kind),400,'Invalid photo variant.');requireThat(bytes.length===Number(thumb?m.thumbnail_bytes:m.bytes)&&hash(bytes)===(thumb?m.thumbnail_checksum:m.checksum),400,'The photo changed during upload. Try again.');requireThat(bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP',415,'Upload a supported photo.');await files.put(thumb?m.thumbnail_key:m.object_key,bytes);return{ok:true};},
  async finalize(e,g,id){const m=await ready(id);requireThat(m.event_id===e.id&&m.guest_id===g.id&&m.status!=='deleted',409,'This event is closed. The photo was not completed.');if(m.status==='uploaded')return {ok:true};requireThat(eventState(e)==='live',409,'This event is closed. The photo was not completed.');for(const[k,h]of [[m.object_key,m.checksum],[m.thumbnail_key,m.thumbnail_checksum]]){let bytes;try{bytes=await files.get(k);}catch{requireThat(false,409,'Both photo files must finish uploading.');}requireThat(hash(bytes)===h,409,'Photo verification failed. Try again.');try{await sharp(bytes,{limitInputPixels:40e6}).raw().toBuffer();}catch{requireThat(false,415,'This file is not a valid photo.');}}const result=await db.query("update media set status='uploaded' where id=$1 and status='pending' and exists(select 1 from events where id=$2 and status='published' and paused=false and starts_at<=now() and ends_at>now()) returning id",[id,e.id]);if(!result.rows.length)requireThat((await ready(id)).status==='uploaded',409,'The event closed while the photo was being verified.');if(result.rows.length)await db.query("insert into metrics(id,event_id,kind,amount) values($1,$2,'upload-completed',1)",[uuid(),e.id]);return{ok:true};},
  async list(e,params){const offset=Math.max(0,Math.min(100000,Number(params.get('offset'))||0));const guest=params.get('guest')||'',date=params.get('date')||'';requireThat(!date||/^\d{4}-\d{2}-\d{2}$/.test(date),400,'Choose a valid date.');const order=params.get('sort')==='oldest'?'asc':'desc';const filters="m.event_id=$1 and m.status='uploaded' and ($2='' or g.name=$2) and ($3='' or (m.created_at at time zone $4)::date::text=$3)";const zone=params.get('time_zone')||e.time_zone;requireThat(zone.length<=80&&DateTime.now().setZone(zone).isValid,400,'Choose a valid date.');const args=[e.id,guest,date,zone];const photos=(await db.query(`select m.id,m.name,m.created_at,m.bytes,g.name as guest from media m join guests g on g.id=m.guest_id where ${filters} order by m.created_at ${order},m.id ${order} limit 24 offset $5`,[...args,offset])).rows;const total=(await db.query(`select count(*)::int as n from media m join guests g on g.id=m.guest_id where ${filters}`,args)).rows[0].n;const guests=(await db.query("select distinct g.name from guests g join media m on m.guest_id=g.id where m.event_id=$1 and m.status='uploaded' order by g.name",[e.id])).rows.map(g=>g.name);return {photos,total,guests,offset,next:offset+photos.length<total?offset+photos.length:null,updated_at:new Date().toISOString()};},
  async remove(user,e,ids){requireThat(Array.isArray(ids)&&ids.length>0&&ids.length<=200,400,'Select 1 to 200 photos.');await db.transaction(async tx=>{const rows=(await tx.query("select id from media where event_id=$1 and id=any($2::uuid[]) and status='uploaded'",[e.id,ids])).rows;requireThat(rows.length===new Set(ids).size,404,'Some selected photos are unavailable.');await tx.query("update media set status='deleted',deleted_at=now() where event_id=$1 and id=any($2::uuid[])",[e.id,ids]);await tx.query('insert into jobs(id,owner_id,event_id,type,payload) values($1,$2,$3,\'media-cleanup\',$4)',[uuid(),user.id,e.id,JSON.stringify({ids})]);});return{ok:true};}
 };
}
