import {readFile,lstat,realpath} from 'node:fs/promises';import {createReadStream} from 'node:fs';import {createHash} from 'node:crypto';import path from 'node:path';
const root=path.resolve(process.argv[2]||'');if(!process.argv[2])throw new Error('Usage: node platform/scripts/verify-backup.mjs <backup-directory>');const manifest=JSON.parse(await readFile(path.join(root,'manifest.json'),'utf8'));
const resolveFile=relative=>{if(typeof relative!=='string'||!relative)throw new Error('Backup manifest contains an invalid file path.');const file=path.resolve(root,relative),inside=path.relative(root,file);if(!inside||inside.startsWith(`..${path.sep}`)||inside==='..'||path.isAbsolute(inside))throw new Error('Backup manifest file path escapes its directory.');return file;};
const realRoot=await realpath(root);
const verifyFile=async({file,size,sha256},label)=>{if(!Number.isSafeInteger(size)||size<0||typeof sha256!=='string'||! /^[a-f0-9]{64}$/i.test(sha256))throw new Error(`Backup manifest has invalid integrity data: ${label}`);const target=await realpath(resolveFile(file)),inside=path.relative(realRoot,target);if(!inside||inside.startsWith(`..${path.sep}`)||inside==='..'||path.isAbsolute(inside))throw new Error('Backup manifest file path escapes its directory.');const info=await lstat(target);if(!info.isFile())throw new Error(`Backup item is not a regular file: ${label}`);if(info.size!==size)throw new Error(`Size mismatch: ${label}`);const hash=createHash('sha256');for await(const chunk of createReadStream(target))hash.update(chunk);if(hash.digest('hex')!==sha256.toLowerCase())throw new Error(`Checksum mismatch: ${label}`);};
if(manifest.format_version!==2||!manifest.database||!Array.isArray(manifest.database.tables)||!Array.isArray(manifest.objects))throw new Error('Backup manifest is incomplete or outdated. Create a new version 2 backup.');
const tableNames=new Set();for(const table of manifest.database.tables){if(table?.schema!=='public'||typeof table.name!=='string'||!table.name||typeof table.rows!=='string'||!/^\d+$/.test(table.rows))throw new Error('Backup manifest contains an invalid database table inventory.');const name=`${table.schema}.${table.name}`;if(tableNames.has(name))throw new Error('Backup manifest contains a duplicate database table.');tableNames.add(name);}
const objectKeys=new Set();for(const object of manifest.objects){if(typeof object?.key!=='string'||!object.key||objectKeys.has(object.key))throw new Error('Backup manifest contains an invalid or duplicate R2 key.');objectKeys.add(object.key);}
await verifyFile(manifest.database,'database dump');
for(const object of manifest.objects)await verifyFile(object,object.key||'unnamed object');
console.log(`Backup verified: database dump and ${manifest.objects.length} R2 objects. Restore into an empty isolated drill environment before approving production.`);
